version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: code_editor
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Navi313@

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis:latest